-- Office Town Cloud — initial D1 schema.
--
-- Generated by hand to match drizzle/schema.ts and to include the FTS5
-- virtual table that drizzle-kit can't generate.

CREATE TABLE IF NOT EXISTS wiki_collections (
	name TEXT PRIMARY KEY,
	shape TEXT NOT NULL,
	canonical_filename TEXT NOT NULL,
	required_fields_json TEXT NOT NULL,
	description TEXT NOT NULL,
	created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS wiki_entries (
	id TEXT PRIMARY KEY,
	collection TEXT NOT NULL,
	slug TEXT NOT NULL,
	r2_key TEXT NOT NULL,
	title TEXT,
	frontmatter_json TEXT NOT NULL,
	body TEXT NOT NULL,
	body_hash TEXT NOT NULL,
	last_change_summary TEXT,
	last_edited_by TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_wiki_entries_collection ON wiki_entries(collection);
CREATE INDEX IF NOT EXISTS idx_wiki_entries_updated_at ON wiki_entries(updated_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_wiki_entries_unique ON wiki_entries(collection, slug);

CREATE TABLE IF NOT EXISTS wiki_vector_index (
	entry_id TEXT PRIMARY KEY,
	vector_id TEXT NOT NULL,
	body_hash TEXT NOT NULL,
	indexed_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS session_log (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	action TEXT NOT NULL,
	target TEXT,
	created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_session_log_user ON session_log(user_id, created_at DESC);

-- Seed the 10 default collections.
INSERT OR IGNORE INTO wiki_collections (name, shape, canonical_filename, required_fields_json, description, created_at) VALUES
	('business',  'flat-topic',         '',           '["name"]',                  'The business this town serves — identity, ABN, HQ, timezone',                       datetime('now')),
	('owner',     'flat-topic',         '',           '[]',                        'Principal user voice, rhythm, bio',                                                 datetime('now')),
	('team',      'entity-as-folder',   'profile.md', '["name"]',                  'Humans + agents on the team',                                                       datetime('now')),
	('contacts',  'entity-as-folder',   'contact.md', '["name"]',                  'External people we interact with',                                                  datetime('now')),
	('orgs',      'entity-as-folder',   'entity.md',  '["name","entity_type"]',    'External organisations — clients, prospects, vendors, partners, competitors',      datetime('now')),
	('projects',  'entity-as-folder',   'project.md', '["name"]',                  'Active and historical projects',                                                    datetime('now')),
	('decisions', 'entity-as-folder',   'decision.md','["title"]',                 'Decisions made — with rationale and date',                                          datetime('now')),
	('knowledge', 'entity-as-folder',   'concept.md', '["title"]',                 'Curated knowledge concepts — patterns, conventions, references',                    datetime('now')),
	('research',  'dated-stream',       '',           '["title"]',                 'Time-stamped investigations, scout findings worth keeping',                         datetime('now')),
	('feedback',  'dated-stream',       '',           '["title"]',                 'User feedback, escalations, retros',                                                datetime('now'));
