#!/usr/bin/env python3
"""Brains-trust panel for Office Town: installer + sync + media pipeline + schema.

Fires three frontier reviewers in parallel via OpenRouter, each returning
Critical/High/Medium/Low findings. Outputs saved to .jez/audits/.
"""
import concurrent.futures
import json
import os
import pathlib
import urllib.request

# Key is read from the env (export OPENROUTER_API_KEY=...) or, failing that,
# from ~/Documents/.jez/secrets/openrouter*.md — never hardcoded/committed.
def _load_key():
    k = os.environ.get("OPENROUTER_API_KEY")
    if k:
        return k.strip()
    import glob
    import re
    for f in glob.glob(os.path.expanduser("~/Documents/.jez/secrets/openrouter*.md")):
        m = re.search(r"sk-or-v1-[A-Za-z0-9]+", pathlib.Path(f).read_text())
        if m:
            return m.group(0)
    raise SystemExit("No OpenRouter key: set OPENROUTER_API_KEY or add it to ~/Documents/.jez/secrets/")


KEY = _load_key()
ROOT = pathlib.Path("/Users/jez/Documents/office-town-cloud")
DAEMON = pathlib.Path("/Users/jez/Documents/officetowd")
OUT = ROOT / ".jez" / "audits"
OUT.mkdir(parents=True, exist_ok=True)

MODELS = {
    "gpt-5.5": "openai/gpt-5.5",
    "opus-4.8": "anthropic/claude-opus-4.8",
    "gemini-3.1-pro": "google/gemini-3.1-pro-preview",
}


def section(title, text):
    return f"\n\n===== {title} =====\n\n{text}\n"


def slice_file(path, start, end):
    lines = path.read_text().splitlines()
    return "\n".join(lines[start - 1 : end])


bundle = ""
bundle += section(
    "FILE: src/mcp-server/files.ts (full — files MCP gateway, convert/vision/video)",
    (ROOT / "src/mcp-server/files.ts").read_text(),
)
bundle += section(
    "FILE: src/bootstrap.ts (full — D1 schema bootstrap + versioning)",
    (ROOT / "src/bootstrap.ts").read_text(),
)
bundle += section(
    "FILE: connect.sh installer (generated by src/dashboard/routes.ts lines 1100-1392)",
    slice_file(ROOT / "src/dashboard/routes.ts", 1100, 1392),
)
bundle += section(
    "FILE: officetowd internal/sync/sync.go (full — bisync engine + mass-delete safety valve)",
    (DAEMON / "internal/sync/sync.go").read_text(),
)

GOALS = """\
PROJECT: Office Town — an open-source, self-hostable "personal cortex" that runs as a
Goose (AI agent) extension on Cloudflare Workers + D1 + R2 + Workers AI. Non-technical
users install it with a one-line curl|bash, dump files into an inbox folder, and an AI
agent learns their business from the documents. A Go sync daemon (officetowd) bisyncs a
local ~/OfficeTown/ folder against R2.

YOUR JOB: Adversarial code review of four recently-built/changed surfaces. Find real
bugs that would bite real users — prioritise:
  - DATA LOSS (this project already had one incident: a stale manifest + empty local
    folder caused a bisync to wipe all R2 objects; a safety valve was added).
  - SECURITY (the installer runs arbitrary shell on a user's Mac, edits their Goose
    config, writes a bearer token to disk; the worker exposes MCP endpoints behind a
    bearer token).
  - CORRECTNESS of the sync 3-way merge, the schema upgrade path, and the media
    conversion (HEIC transcode, video frame extraction, content-hash cache, sidecar
    writes).
  - PLATFORM GOTCHAS specific to Cloudflare Workers / D1 / Workers AI / R2 / Go.

CONTEXT THE REVIEWER SHOULD KNOW:
  - files.ts `convert`: routes images -> Gemma 4 multimodal description (HEIC/HEIF are
    transcoded to JPEG via env.IMAGES first), video -> per-frame sequence + Whisper
    audio, else -> env.AI.toMarkdown. Results cached in D1 `convert_cache` keyed by
    sha256(original bytes)+variant. Converted markdown saved as a sidecar `<name>.md`
    beside the original in R2 (bucketForKey routes wiki/ -> WIKI bucket else FILES).
  - bootstrap.ts: a fresh Deploy-to-Cloudflare DB has no tables; ensureSchema applies an
    idempotent statement array. Now versioned so upgrades replay to add new tables.
  - sync.go: three-way per-path compare (local walk vs remote list vs manifest). A
    safety valve blocks opDeleteRemote when planned remote deletions exceed
    max(10, len(remote)/2).

OUTPUT FORMAT — be specific, cite file + the code, and rank each finding:
  ## CRITICAL  (data loss, auth bypass, guaranteed-fire bug)
  ## HIGH      (likely bug, security weakness, breaks a common path)
  ## MEDIUM    (edge case, correctness gap, maintainability risk)
  ## LOW       (nit, style, minor robustness)
For each: a one-line title, the file+location, what goes wrong, and the fix. Skip
findings you're not confident are real. Don't pad with generic advice. If something is
actually well-handled, a short "Strengths" note at the end is welcome but optional.
"""


def call(name, model):
    payload = json.dumps(
        {
            "model": model,
            "messages": [
                {"role": "system", "content": "You are a meticulous senior engineer doing an adversarial pre-commit review. You find real, specific bugs and cite exact code. You do not invent issues or pad."},
                {"role": "user", "content": GOALS + "\n\n# CODE UNDER REVIEW\n" + bundle},
            ],
        }
    ).encode()
    req = urllib.request.Request(
        "https://openrouter.ai/api/v1/chat/completions",
        data=payload,
        headers={
            "Authorization": f"Bearer {KEY}",
            "Content-Type": "application/json",
            "X-Title": "Office Town brains-trust 2026-05-29",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=600) as resp:
            data = json.load(resp)
        content = data["choices"][0]["message"]["content"]
        usage = data.get("usage", {})
        out = OUT / f"2026-05-29-brains-trust-{name}.md"
        out.write_text(f"# Brains-trust review — {name} ({model})\n\n{content}\n")
        return name, "ok", usage, len(content)
    except urllib.error.HTTPError as e:
        body = e.read().decode()[:500]
        return name, f"HTTP {e.code}: {body}", {}, 0
    except Exception as e:  # noqa
        return name, f"ERR {e}", {}, 0


with concurrent.futures.ThreadPoolExecutor(max_workers=3) as ex:
    futs = [ex.submit(call, n, m) for n, m in MODELS.items()]
    for f in concurrent.futures.as_completed(futs):
        name, status, usage, n = f.result()
        print(f"[{name}] {status} | chars={n} | usage={usage}")

print(f"\nBundle size: {len(bundle)} chars (~{len(bundle)//4} tokens)")
print(f"Outputs in {OUT}")
